environment: test

paths:
  data_root: .data
  chroma_db_dir: .data/chroma_db
  sqlite_path: .data/sqlite/tables.db
  logs_path: .data/logs/app.log
  output_dir: .data/outputs

llm:
  mode: prod
  connector: llm_connectors.connector_prod.call_llm

  # ===== НАСТРОЙКИ КОРПОРАТИВНОЙ LLM (OpenAI-совместимый формат) =====
  base_url: "https://YOUR-CORPORATE-LLM-URL/v1"
  api_key: "YOUR_CORPORATE_LLM_TOKEN_HERE"
  model: "YOUR_CORPORATE_MODEL_NAME"

access_control:
  allow_corporate_in_dev: false
