environment: dev  # dev | test | prod

paths:
  data_root: "./data"
  chromadb_dir: "./data/chromadb"
  sqlite_path: "./data/sqlite/tables.db"
  logs_path: "./data/logs/app.log"

llm:
  # mode:
  #   dev  - локальная модель через connector_dev
  #   test - можно использовать тот же коннектор или отдельный стенд
  #   prod - боевой коннектор (добавишь позже в llm_connectors.connector_prod)
  mode: dev
  connector: "llm_connectors.connector_dev:call_llm"
